spring.application.name=sistema-locadora

# Configurações do servidor
server.port=8080
server.error.include-binding-errors=always

# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_locadora?useSSL=false
spring.datasource.username=java
spring.datasource.password=Senha@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do jpa e hibernate
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Swagger
springdoc.swagger-ui.enabled=true